\ fcov.4th — entry point for the fcov coverage tool.
\
\ fcov is a coverage collector for Forth source trees. It runs your
\ tests under instrumentation, then reports which `:`-defined words
\ were actually exercised (and, in a future release, which IF/ELSE
\ branches inside them).
\
\ As of 0.2.0, the run/report pipeline is real:
\
\   1. `fcov run [<test-cmd>]` walks the project tree (via fcov/walk),
\      tokenises every .4th file (fcov/scan), generates a per-process
\      instrumentation prelude (fcov/prelude) and a `.fcov/bin/gforth`
\      shim, then executes the user-supplied test command with
\      `.fcov/bin/` first on PATH so any subprocess that calls `gforth`
\      gets pre-loaded with the prelude. Per-process call shards land
\      in `.fcov/calls/<pid>.log`.
\
\   2. After the test command exits, fcov ingests the call shards,
\      writes `.fcov/coverage.json` (canonical) and prints a console
\      summary.
\
\   3. `fcov report [--format console|lcov]` re-walks the source tree,
\      re-ingests `.fcov/calls/`, and renders the requested format.
\
\ See doc/ROADMAP.md for branch-coverage plans (1.0.0+) and design
\ notes on the subprocess fan-out and prelude design.

require fcov/util.4th

\ --- Self-version (read from package.4th) ---------------------------------

2variable fcov-ver-data
s" unknown" fcov-ver-data 2!

[UNDEFINED] fcov-home-path [IF]
: fcov-home-path ( -- a u )
    s" FCOV_HOME" getenv 2dup nip IF EXIT THEN
    2drop s" HOME" getenv s" /fcov" fcov.str-concat ;
[THEN]

\ Throwaway parser for package.4th — captures `key-value version <X>`.
MARKER fcov.discard-ver-parser

: forth-package ;
: end-forth-package ;
: key-list 0 parse 2drop ;
: key-value
    parse-name s" version" compare 0= IF
        parse-name fcov.str-dup fcov-ver-data 2!
    ELSE
        0 parse 2drop
    THEN ;

: fcov.read-self-version
    fcov-home-path s" /package.4th" fcov.str-concat { buf bu }
    buf bu 2dup file-status nip 0= IF
        included
    ELSE
        2drop
    THEN
    buf free throw ;

fcov.read-self-version

fcov.discard-ver-parser

\ Version-check parser uses its own throwaway scope; load *after* the
\ self-version parser is gone to avoid colliding key-value/key-list defs.
require fcov/version-check.4th

\ --- 0.2.0 pipeline modules -----------------------------------------------

require fcov/walk.4th
require fcov/scan.4th
require fcov/collect.4th
require fcov/exclude.4th
require fcov/prelude.4th
require fcov/aggregate.4th
require fcov/report-console.4th
require fcov/report-lcov.4th
require fcov/report-json.4th
require fcov/report-html.4th

\ --- Argument parsing -----------------------------------------------------

2variable fcov.cmd
2variable fcov.arg
2variable fcov.rest
2variable fcov.cwd
s" " fcov.cmd 2!
s" " fcov.arg 2!
s" " fcov.rest 2!
s" " fcov.cwd 2!

: fcov.read-args
    s" FCOV_CMD" getenv 2dup nip IF
        fcov.str-dup fcov.cmd 2!
    ELSE
        2drop s" help" fcov.cmd 2!
    THEN
    s" FCOV_ARG" getenv 2dup nip IF
        fcov.str-dup fcov.arg 2!
    ELSE
        2drop s" " fcov.arg 2!
    THEN
    s" FCOV_REST" getenv 2dup nip IF
        fcov.str-dup fcov.rest 2!
    ELSE
        2drop s" " fcov.rest 2!
    THEN
    s" FCOV_CWD" getenv 2dup nip IF
        fcov.str-dup fcov.cwd 2!
    ELSE
        2drop pad 4096 get-dir fcov.str-dup fcov.cwd 2!
    THEN ;

\ --- Common helpers -------------------------------------------------------

\ Build "<cwd>/<rel>" → fresh string. Caller frees.
: fcov.abs-path { rel-a rel-u -- a u }
    fcov.cwd 2@ rel-a rel-u fcov.fs-join ;

: fcov.path-exists? { a u -- f }
    a u file-status nip 0= ;

\ --- Walk + scan ----------------------------------------------------------

: fcov.scan-if-not-excluded ( path-a path-u -- )
    2dup fcov.path-excluded? IF 2drop EXIT THEN
    fcov.scan-file ;

: fcov.collect-defs
    fcov.recs-clear
    s" ." fcov.walk-collect
    ['] fcov.scan-if-not-excluded fcov.walk-foreach
    \ ulist-add prepends; reverse once so iterators yield records in
    \ walk order (file-by-file, top-to-bottom) — matches what humans
    \ expect when reading defs.json or the console table.
    fcov.recs-reverse ;

\ --- run command ----------------------------------------------------------

: fcov.test-cmd ( -- a u )
    \ default = «fmix test»; otherwise concat arg + " " + rest. Always
    \ returns a heap-allocated buffer so the caller can free uniformly.
    fcov.arg 2@ nip 0= IF s" fmix test" fcov.str-dup EXIT THEN
    fcov.rest 2@ nip 0= IF fcov.arg 2@ fcov.str-dup EXIT THEN
    fcov.arg 2@ s"  " fcov.str-concat { ia iu }
    ia iu fcov.rest 2@ fcov.str-concat
    ia free throw ;

: fcov.write-shim { shim-fid -- }
    s\" #!/usr/bin/env bash\n" shim-fid write-file throw
    s\" # auto-generated by fcov; do not edit.\n" shim-fid write-file throw
    s\" # re-execs the real gforth with the fcov prelude pre-loaded.\n" shim-fid write-file throw
    s\" set -e\n" shim-fid write-file throw
    s\" : ${FCOV_REAL_GFORTH:?fcov: FCOV_REAL_GFORTH not set}\n" shim-fid write-file throw
    s\" : ${FCOV_PRELUDE:?fcov: FCOV_PRELUDE not set}\n" shim-fid write-file throw
    s\" : ${FCOV_CALLS_DIR:?fcov: FCOV_CALLS_DIR not set}\n" shim-fid write-file throw
    s" # Always derive a per-PID shard so concurrent / nested gforth" shim-fid write-line throw
    s" # subprocesses don't truncate each other's logs (the prelude" shim-fid write-line throw
    s" # opens FCOV_CALLS_LOG with w/o create-file). Tests that need" shim-fid write-line throw
    s" # to read shards back should override FCOV_CALLS_DIR instead." shim-fid write-line throw
    s\" export FCOV_CALLS_LOG=\"${FCOV_CALLS_DIR}/calls.$$.log\"\n" shim-fid write-file throw
    s\" exec \"$FCOV_REAL_GFORTH\" -e \"include $FCOV_PRELUDE\" \"$@\"\n" shim-fid write-file throw ;

: fcov.write-runner-script { rs-fid prelude-a prelude-u callsdir-a callsdir-u shimdir-a shimdir-u testcmd-a testcmd-u -- }
    s\" #!/usr/bin/env bash\n" rs-fid write-file throw
    s\" # auto-generated by fcov; do not edit.\n" rs-fid write-file throw
    s\" set +e\n" rs-fid write-file throw

    s\" export FCOV_REAL_GFORTH=\"${FCOV_REAL_GFORTH:-$(command -v gforth)}\"\n"
        rs-fid write-file throw
    s\" export FCOV_PRELUDE=\"" rs-fid write-file throw
    prelude-a prelude-u rs-fid write-file throw
    s\" \"\n" rs-fid write-file throw

    s\" export FCOV_CALLS_DIR=\"" rs-fid write-file throw
    callsdir-a callsdir-u rs-fid write-file throw
    s\" \"\n" rs-fid write-file throw

    s\" export PATH=\"" rs-fid write-file throw
    shimdir-a shimdir-u rs-fid write-file throw
    s\" :$PATH\"\n" rs-fid write-file throw

    s" " rs-fid write-line throw
    testcmd-a testcmd-u rs-fid write-line throw ;

: fcov.run-prepare-tree
    s" .fcov"        fcov.mkdir-p
    s" .fcov/bin"    fcov.mkdir-p
    s" .fcov/calls"  fcov.mkdir-p
    \ make sure no stale shards from a previous run pollute the merge.
    s" rm -f .fcov/calls/*.log" fcov.str-dup fcov.shell-1 ;

: fcov.run
    fcov.run-prepare-tree
    fcov.collect-defs

    \ ---- defs.json (informational; not consumed by report) ----
    s" .fcov/defs.json" fcov.write-defs-json

    \ ---- prelude ----
    s" .fcov/_prelude.4th" fcov.write-prelude

    \ ---- shim ----
    s" .fcov/bin/gforth" w/o create-file throw { shim-fid }
    shim-fid fcov.write-shim
    shim-fid close-file throw
    s" .fcov/bin/gforth" fcov.chmod+x

    \ ---- runner script (env exports + exec test-cmd) ----
    fcov.test-cmd { tc-a tc-u }
    s" .fcov/_prelude.4th"         fcov.abs-path { p-a p-u }
    s" .fcov/calls"                fcov.abs-path { c-a c-u }
    s" .fcov/bin"                  fcov.abs-path { s-a s-u }

    s" .fcov/_run.sh" w/o create-file throw { rs-fid }
    rs-fid p-a p-u c-a c-u s-a s-u tc-a tc-u fcov.write-runner-script
    rs-fid close-file throw
    s" .fcov/_run.sh" fcov.chmod+x

    cr s" * fcov: instrumenting " type
    fcov.recs-count fcov.u>str type
    s"  word definition(s); running: " type tc-a tc-u type cr

    \ ---- exec the user's test command ----
    s" bash .fcov/_run.sh" fcov.str-dup fcov.shell-1

    \ ---- aggregate shards ----
    fcov.hits-clear
    s" .fcov/calls" fcov.ingest-calls-dir

    \ ---- write coverage.json ----
    s" .fcov/coverage.json"
    tc-a tc-u
    fcov-ver-data 2@
    fcov.write-coverage-json

    \ ---- always print console report at the end of run ----
    fcov.report-console

    \ ---- cleanup ----
    p-a p-u drop free throw
    c-a c-u drop free throw
    s-a s-u drop free throw
    tc-a tc-u drop free throw ;

\ --- report command -------------------------------------------------------

: fcov.report-format ( -- a u )
    fcov.arg 2@ s" --format" compare 0= IF
        fcov.rest 2@ nip 0<> IF fcov.rest 2@ EXIT THEN
    THEN
    fcov.arg 2@ s" --format=" fcov.starts-with? IF
        fcov.arg 2@ swap 9 + swap 9 - EXIT
    THEN
    s" console" ;

: fcov.report
    fcov.collect-defs
    fcov.hits-clear
    s" .fcov/calls" fcov.ingest-calls-dir
    fcov.report-format { fa fu }
    fa fu s" json"    compare 0= IF fcov.report-json     EXIT THEN
    fa fu s" html"    compare 0= IF fcov.report-html     EXIT THEN
    fa fu s" lcov"    compare 0= IF fcov.report-lcov     EXIT THEN
    fa fu s" console" compare 0= IF fcov.report-console  EXIT THEN
    cr s" [WARN] unknown --format `" type fa fu type
    s" `; defaulting to console." type cr
    fcov.report-console ;

\ --- help -----------------------------------------------------------------

: fcov.help
    cr s" fcov v" type fcov-ver-data 2@ type
    s"  — coverage collector for Forth source trees" type cr
    s" Usage: fcov <command> [args]" type cr
    s" Commands:" type cr
    s"    run [<test-cmd>]                          - Run tests under instrumentation" type cr
    s"                                                (default: `fmix test`)." type cr
    s"    report [--format <fmt>]                   - Show coverage report from last run." type cr
    s"    clean                                     - Remove .fcov/ artefacts." type cr
    s"    version                                   - Show fcov version." type cr
    s"    help                                      - Show this help." type cr cr
    s" Report formats (--format <fmt>):" type cr
    s"    console (default) - colourised table to stdout, grep-friendly." type cr
    s"    json              - canonical .fcov/coverage.json dumped to stdout;" type cr
    s"                        consume from `jq`, dashboards, custom tools." type cr
    s"    lcov              - LCOV trace data (.info-style) to stdout;" type cr
    s"                        feed into genhtml or any LCOV-aware tooling." type cr
    s"    html              - self-contained static site under .fcov/html/" type cr
    s"                        (index.html + per-file pages with covered/" type cr
    s"                        uncovered word highlighting)." type cr cr
    s" Notes:" type cr
    s"    - measures *definition coverage*: `:`-defined words. Branch" type cr
    s"      coverage (IF/ELSE/?DO/…) is the goal for 1.0.0." type cr
    s"    - build/ and forth-packages/ subdirectories are excluded from the walk." type cr
    s"    - Hidden files/dirs (anything starting with `.`) are excluded too." type cr
    s"    - `key-list fcov-exclude <prefix>` in package.4th excludes more paths." type cr cr ;

: fcov.version
    cr s" ** (fcov) v" type fcov-ver-data 2@ type cr cr ;

\ --- clean ----------------------------------------------------------------

: fcov.clean
    s" rm -rf .fcov/" fcov.str-dup fcov.shell-1
    cr s" * fcov: removed .fcov/ (if it existed)." type cr ;

: fcov-dispatch
    fcov.read-args
    fcov.check-required-version
    fcov.cmd 2@ s" run"     compare 0= IF fcov.run     EXIT THEN
    fcov.cmd 2@ s" report"  compare 0= IF fcov.report  EXIT THEN
    fcov.cmd 2@ s" clean"   compare 0= IF fcov.clean   EXIT THEN
    fcov.cmd 2@ s" version" compare 0= IF fcov.version EXIT THEN
    fcov.cmd 2@ s" help"    compare 0= IF fcov.help    EXIT THEN
    cr s" Unknown command: " type fcov.cmd 2@ type cr
    fcov.help
    1 (bye) ;

fcov-dispatch
0 (bye)
