\ fcov/prelude.4th — generates `./.fcov/_prelude.4th`.
\
\ The prelude is a self-contained Forth file pre-loaded into every
\ gforth subprocess spawned during `fcov run`. It redefines `:` so
\ every fresh colon-definition compiles a one-shot logging call into
\ its own body. Subsequent invocations of that word emit the word's
\ name to a per-process append-only log under .fcov/calls/.
\
\ Gforth specificity:
\   - `latestxt >name name>string` is gforth's documented idiom for
\     «name of the word just defined». Other Forths require their own
\     equivalent (e.g. `last @ name>string` on some old gforths). The
\     prelude is regenerated on every `fcov run`, so future versions
\     can ship per-Forth variants here without touching the runner.
\
\ Layout of the produced prelude:
\
\   1. `[UNDEFINED] fcov.hit [IF]` guard (idempotent; safe to load twice).
\   2. log-file management: lazy open of .fcov/calls.<pid>.log via
\      $FCOV_CALLS_LOG (set by the .fcov/bin/gforth wrapper).
\   3. `fcov.hit ( name-a name-u -- )`: writes one name per line.
\   4. Save original `:` as `fcov.orig-colon` and redefine `:` to
\      append `fcov.hit` to the body of every new colon-def.
\   5. `[THEN]` to close the guard.
\
\ The prelude is plain Forth text — no fcov-private vocabulary leaks
\ into the user's session beyond `fcov.*` names.

require fcov/util.4th

variable fcov.prelude-fid    0 fcov.prelude-fid !

: fcov.prelude-line ( a u -- )
    fcov.prelude-fid @ write-line throw ;

\ --- The prelude content -------------------------------------------------
\
\ Each `fcov.prelude-line` appends one source line + a newline. We don't
\ try to be clever about template substitution: the content is fixed, the
\ runtime variables (log path, real gforth) are resolved by env vars at
\ subprocess start.

: fcov.emit-prelude
    s" \ .fcov/_prelude.4th — auto-generated by fcov; do not edit."     fcov.prelude-line
    s" \"                                                               fcov.prelude-line
    s" \ Loaded into every gforth subprocess spawned during `fcov run`." fcov.prelude-line
    s" \ Redefines `:` so that every new colon-def writes its own name" fcov.prelude-line
    s" \ to .fcov/calls/<pid>.log on each call. The aggregator merges"  fcov.prelude-line
    s" \ those shards against the static catalogue produced by the"     fcov.prelude-line
    s" \ walker."                                                       fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s" [UNDEFINED] fcov.hit [IF]"                                       fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s" \ --- log file (append-only, one shard per gforth process) ---"  fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s" variable fcov.log-fid    0 fcov.log-fid !"                       fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s" : fcov.log-default-path ( -- a u )"                              fcov.prelude-line
    s\"     s\" .fcov/calls/default.log\" ;"                            fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s" : fcov.log-path ( -- a u )"                                      fcov.prelude-line
    s\"     s\" FCOV_CALLS_LOG\" getenv 2dup nip 0= IF"                 fcov.prelude-line
    s" 	2drop fcov.log-default-path"                                fcov.prelude-line
    s" 	THEN ;"                                                     fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s" : fcov.log-open"                                                 fcov.prelude-line
    s" 	fcov.log-fid @ IF EXIT THEN"                                fcov.prelude-line
    s" 	fcov.log-path w/o create-file throw fcov.log-fid ! ;"       fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s" : fcov.hit ( name-a name-u -- )"                                 fcov.prelude-line
    s" 	fcov.log-open"                                              fcov.prelude-line
    s" 	fcov.log-fid @ write-line throw"                            fcov.prelude-line
    s" 	fcov.log-fid @ flush-file throw ;"                          fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s" \ --- redefine : -----------------------------------------------" fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s\" ' : value fcov.orig-colon"                                      fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s\" : :"                                                            fcov.prelude-line
    s" 	fcov.orig-colon execute"                                    fcov.prelude-line
    s" 	latestxt >name name>string"                                 fcov.prelude-line
    s" 	swap postpone literal"                                      fcov.prelude-line
    s" 	postpone literal"                                           fcov.prelude-line
    s" 	postpone fcov.hit ;"                                        fcov.prelude-line
    s" "                                                                fcov.prelude-line
    s" [THEN]"                                                          fcov.prelude-line
    ;

: fcov.write-prelude { fname-a fname-u -- }
    fname-a fname-u w/o create-file throw fcov.prelude-fid !
    fcov.emit-prelude
    fcov.prelude-fid @ close-file throw
    0 fcov.prelude-fid ! ;
